export interface Country {
  name: string;
  code: string;
  flag: string;
}

export const countries: Country[] = [
  { name: 'Afeganistão', code: '+93', flag: '🇦🇫' },
  { name: 'África do Sul', code: '+27', flag: '🇿🇦' },
  { name: 'Albânia', code: '+355', flag: '🇦🇱' },
  { name: 'Alemanha', code: '+49', flag: '🇩🇪' },
  { name: 'Andorra', code: '+376', flag: '🇦🇩' },
  { name: 'Angola', code: '+244', flag: '🇦🇴' },
  { name: 'Anguila', code: '+1', flag: '🇦🇮' },
  { name: 'Antártida', code: '+672', flag: '🇦🇶' },
  { name: 'Antígua e Barbuda', code: '+1', flag: '🇦🇬' },
  { name: 'Arábia Saudita', code: '+966', flag: '🇸🇦' },
  { name: 'Argélia', code: '+213', flag: '🇩🇿' },
  { name: 'Argentina', code: '+54', flag: '🇦🇷' },
  { name: 'Armênia', code: '+374', flag: '🇦🇲' },
  { name: 'Aruba', code: '+297', flag: '🇦🇼' },
  { name: 'Austrália', code: '+61', flag: '🇦🇺' },
  { name: 'Áustria', code: '+43', flag: '🇦🇹' },
  { name: 'Azerbaijão', code: '+994', flag: '🇦🇿' },
  { name: 'Bahamas', code: '+1', flag: '🇧🇸' },
  { name: 'Bangladexe', code: '+880', flag: '🇧🇩' },
  { name: 'Barbados', code: '+1', flag: '🇧🇧' },
  { name: 'Barém', code: '+973', flag: '🇧🇭' },
  { name: 'Bélgica', code: '+32', flag: '🇧🇪' },
  { name: 'Belize', code: '+501', flag: '🇧🇿' },
  { name: 'Benim', code: '+229', flag: '🇧🇯' },
  { name: 'Bermudas', code: '+1', flag: '🇧🇲' },
  { name: 'Bielorrússia', code: '+375', flag: '🇧🇾' },
  { name: 'Bolívia', code: '+591', flag: '🇧🇴' },
  { name: 'Bonaire', code: '+599', flag: '🇧🇶' },
  { name: 'Bósnia e Herzegovina', code: '+387', flag: '🇧🇦' },
  { name: 'Botsuana', code: '+267', flag: '🇧🇼' },
  { name: 'Brasil', code: '+55', flag: '🇧🇷' },
  { name: 'Brunei', code: '+673', flag: '🇧🇳' },
  { name: 'Bulgária', code: '+359', flag: '🇧🇬' },
  { name: 'Burquina Faso', code: '+226', flag: '🇧🇫' },
  { name: 'Burundi', code: '+257', flag: '🇧🇮' },
  { name: 'Butão', code: '+975', flag: '🇧🇹' },
  { name: 'Cabo Verde', code: '+238', flag: '🇨🇻' },
  { name: 'Camarões', code: '+237', flag: '🇨🇲' },
  { name: 'Camboja', code: '+855', flag: '🇰🇭' },
  { name: 'Canadá', code: '+1', flag: '🇨🇦' },
  { name: 'Catar', code: '+974', flag: '🇶🇦' },
  { name: 'Cazaquistão', code: '+7', flag: '🇰🇿' },
  { name: 'Chade', code: '+235', flag: '🇹🇩' },
  { name: 'Chéquia', code: '+420', flag: '🇨🇿' },
  { name: 'Chile', code: '+56', flag: '🇨🇱' },
  { name: 'China', code: '+86', flag: '🇨🇳' },
  { name: 'Chipre', code: '+357', flag: '🇨🇾' },
  { name: 'Colômbia', code: '+57', flag: '🇨🇴' },
  { name: 'Comores', code: '+269', flag: '🇰🇲' },
  { name: 'Coreia do Norte', code: '+850', flag: '🇰🇵' },
  { name: 'Coreia do Sul', code: '+82', flag: '🇰🇷' },
  { name: 'Costa do Marfim', code: '+225', flag: '🇨🇮' },
  { name: 'Costa Rica', code: '+506', flag: '🇨🇷' },
  { name: 'Croácia', code: '+385', flag: '🇭🇷' },
  { name: 'Cuba', code: '+53', flag: '🇨🇺' },
  { name: 'Curaçau', code: '+599', flag: '🇨🇼' },
  { name: 'Dinamarca', code: '+45', flag: '🇩🇰' },
  { name: 'Djibouti', code: '+253', flag: '🇩🇯' },
  { name: 'Dominica', code: '+1', flag: '🇩🇲' },
  { name: 'Egito', code: '+20', flag: '🇪🇬' },
  { name: 'El Salvador', code: '+503', flag: '🇸🇻' },
  { name: 'Emirados Árabes Unidos', code: '+971', flag: '🇦🇪' },
  { name: 'Equador', code: '+593', flag: '🇪🇨' },
  { name: 'Eritreia', code: '+291', flag: '🇪🇷' },
  { name: 'Eslováquia', code: '+421', flag: '🇸🇰' },
  { name: 'Eslovênia', code: '+386', flag: '🇸🇮' },
  { name: 'Espanha', code: '+34', flag: '🇪🇸' },
  { name: 'Estados Unidos', code: '+1', flag: '🇺🇸' },
  { name: 'Estônia', code: '+372', flag: '🇪🇪' },
  { name: 'Etiópia', code: '+251', flag: '🇪🇹' },
  { name: 'Fiji', code: '+679', flag: '🇫🇯' },
  { name: 'Filipinas', code: '+63', flag: '🇵🇭' },
  { name: 'Finlândia', code: '+358', flag: '🇫🇮' },
  { name: 'França', code: '+33', flag: '🇫🇷' },
  { name: 'Gabão', code: '+241', flag: '🇬🇦' },
  { name: 'Gâmbia', code: '+220', flag: '🇬🇲' },
  { name: 'Gana', code: '+233', flag: '🇬🇭' },
  { name: 'Geórgia', code: '+995', flag: '🇬🇪' },
  { name: 'Gibraltar', code: '+350', flag: '🇬🇮' },
  { name: 'Granada', code: '+1', flag: '🇬🇩' },
  { name: 'Grécia', code: '+30', flag: '🇬🇷' },
  { name: 'Gronelândia', code: '+299', flag: '🇬🇱' },
  { name: 'Guadalupe', code: '+590', flag: '🇬🇵' },
  { name: 'Guame', code: '+1', flag: '🇬🇺' },
  { name: 'Guatemala', code: '+502', flag: '🇬🇹' },
  { name: 'Guiana', code: '+592', flag: '🇬🇾' },
  { name: 'Guiana Francesa', code: '+594', flag: '🇬🇫' },
  { name: 'Guiné', code: '+224', flag: '🇬🇳' },
  { name: 'Guiné Equatorial', code: '+240', flag: '🇬🇶' },
  { name: 'Guiné-Bissau', code: '+245', flag: '🇬🇼' },
  { name: 'Haiti', code: '+509', flag: '🇭🇹' },
  { name: 'Honduras', code: '+504', flag: '🇭🇳' },
  { name: 'Hong Kong', code: '+852', flag: '🇭🇰' },
  { name: 'Hungria', code: '+36', flag: '🇭🇺' },
  { name: 'Iémen', code: '+967', flag: '🇾🇪' },
  { name: 'Ilha de Man', code: '+44', flag: '🇮🇲' },
  { name: 'Ilhas Caimão', code: '+1', flag: '🇰🇾' },
  { name: 'Ilhas Cook', code: '+682', flag: '🇨🇰' },
  { name: 'Ilhas Feroé', code: '+298', flag: '🇫🇴' },
  { name: 'Ilhas Malvinas', code: '+500', flag: '🇫🇰' },
  { name: 'Ilhas Marianas do Norte', code: '+1', flag: '🇲🇵' },
  { name: 'Ilhas Marshall', code: '+692', flag: '🇲🇭' },
  { name: 'Ilhas Salomão', code: '+677', flag: '🇸🇧' },
  { name: 'Ilhas Turcas e Caicos', code: '+1', flag: '🇹🇨' },
  { name: 'Ilhas Virgens Americanas', code: '+1', flag: '🇻🇮' },
  { name: 'Ilhas Virgens Britânicas', code: '+1', flag: '🇻🇬' },
  { name: 'Índia', code: '+91', flag: '🇮🇳' },
  { name: 'Indonésia', code: '+62', flag: '🇮🇩' },
  { name: 'Irão', code: '+98', flag: '🇮🇷' },
  { name: 'Iraque', code: '+964', flag: '🇮🇶' },
  { name: 'Irlanda', code: '+353', flag: '🇮🇪' },
  { name: 'Islândia', code: '+354', flag: '🇮🇸' },
  { name: 'Israel', code: '+972', flag: '🇮🇱' },
  { name: 'Itália', code: '+39', flag: '🇮🇹' },
  { name: 'Jamaica', code: '+1', flag: '🇯🇲' },
  { name: 'Japão', code: '+81', flag: '🇯🇵' },
  { name: 'Jersey', code: '+44', flag: '🇯🇪' },
  { name: 'Jordânia', code: '+962', flag: '🇯🇴' },
  { name: 'Kiribati', code: '+686', flag: '🇰🇮' },
  { name: 'Kuwait', code: '+965', flag: '🇰🇼' },
  { name: 'Laos', code: '+856', flag: '🇱🇦' },
  { name: 'Lesoto', code: '+266', flag: '🇱🇸' },
  { name: 'Letônia', code: '+371', flag: '🇱🇻' },
  { name: 'Líbano', code: '+961', flag: '🇱🇧' },
  { name: 'Libéria', code: '+231', flag: '🇱🇷' },
  { name: 'Líbia', code: '+218', flag: '🇱🇾' },
  { name: 'Liechtenstein', code: '+423', flag: '🇱🇮' },
  { name: 'Lituânia', code: '+370', flag: '🇱🇹' },
  { name: 'Luxemburgo', code: '+352', flag: '🇱🇺' },
  { name: 'Macau', code: '+853', flag: '🇲🇴' },
  { name: 'Macedônia do Norte', code: '+389', flag: '🇲🇰' },
  { name: 'Madagascar', code: '+261', flag: '🇲🇬' },
  { name: 'Malásia', code: '+60', flag: '🇲🇾' },
  { name: 'Maláui', code: '+265', flag: '🇲🇼' },
  { name: 'Maldivas', code: '+960', flag: '🇲🇻' },
  { name: 'Mali', code: '+223', flag: '🇲🇱' },
  { name: 'Malta', code: '+356', flag: '🇲🇹' },
  { name: 'Marrocos', code: '+212', flag: '🇲🇦' },
  { name: 'Martinica', code: '+596', flag: '🇲🇶' },
  { name: 'Maurícia', code: '+230', flag: '🇲🇺' },
  { name: 'Mauritânia', code: '+222', flag: '🇲🇷' },
  { name: 'Maiote', code: '+262', flag: '🇾🇹' },
  { name: 'México', code: '+52', flag: '🇲🇽' },
  { name: 'Mianmar', code: '+95', flag: '🇲🇲' },
  { name: 'Micronésia', code: '+691', flag: '🇫🇲' },
  { name: 'Moçambique', code: '+258', flag: '🇲🇿' },
  { name: 'Moldávia', code: '+373', flag: '🇲🇩' },
  { name: 'Mónaco', code: '+377', flag: '🇲🇨' },
  { name: 'Mongólia', code: '+976', flag: '🇲🇳' },
  { name: 'Montenegro', code: '+382', flag: '🇲🇪' },
  { name: 'Monserrate', code: '+1', flag: '🇲🇸' },
  { name: 'Namíbia', code: '+264', flag: '🇳🇦' },
  { name: 'Nauru', code: '+674', flag: '🇳🇷' },
  { name: 'Nepal', code: '+977', flag: '🇳🇵' },
  { name: 'Nicarágua', code: '+505', flag: '🇳🇮' },
  { name: 'Níger', code: '+227', flag: '🇳🇪' },
  { name: 'Nigéria', code: '+234', flag: '🇳🇬' },
  { name: 'Niue', code: '+683', flag: '🇳🇺' },
  { name: 'Noruega', code: '+47', flag: '🇳🇴' },
  { name: 'Nova Caledônia', code: '+687', flag: '🇳🇨' },
  { name: 'Nova Zelândia', code: '+64', flag: '🇳🇿' },
  { name: 'Omã', code: '+968', flag: '🇴🇲' },
  { name: 'Países Baixos', code: '+31', flag: '🇳🇱' },
  { name: 'Palau', code: '+680', flag: '🇵🇼' },
  { name: 'Palestina', code: '+970', flag: '🇵🇸' },
  { name: 'Panamá', code: '+507', flag: '🇵🇦' },
  { name: 'Papua Nova Guiné', code: '+675', flag: '🇵🇬' },
  { name: 'Paquistão', code: '+92', flag: '🇵🇰' },
  { name: 'Paraguai', code: '+595', flag: '🇵🇾' },
  { name: 'Peru', code: '+51', flag: '🇵🇪' },
  { name: 'Polinésia Francesa', code: '+689', flag: '🇵🇫' },
  { name: 'Polônia', code: '+48', flag: '🇵🇱' },
  { name: 'Porto Rico', code: '+1', flag: '🇵🇷' },
  { name: 'Portugal', code: '+351', flag: '🇵🇹' },
  { name: 'Quênia', code: '+254', flag: '🇰🇪' },
  { name: 'Quirguistão', code: '+996', flag: '🇰🇬' },
  { name: 'Reino Unido', code: '+44', flag: '🇬🇧' },
  { name: 'República Centro-Africana', code: '+236', flag: '🇨🇫' },
  { name: 'República do Congo', code: '+242', flag: '🇨🇬' },
  { name: 'República Democrática do Congo', code: '+243', flag: '🇨🇩' },
  { name: 'República Dominicana', code: '+1', flag: '🇩🇴' },
  { name: 'Reunião', code: '+262', flag: '🇷🇪' },
  { name: 'Romênia', code: '+40', flag: '🇷🇴' },
  { name: 'Ruanda', code: '+250', flag: '🇷🇼' },
  { name: 'Rússia', code: '+7', flag: '🇷🇺' },
  { name: 'Saara Ocidental', code: '+212', flag: '🇪🇭' },
  { name: 'Samoa', code: '+685', flag: '🇼🇸' },
  { name: 'Samoa Americana', code: '+1', flag: '🇦🇸' },
  { name: 'Santa Helena', code: '+290', flag: '🇸🇭' },
  { name: 'Santa Lúcia', code: '+1', flag: '🇱🇨' },
  { name: 'São Bartolomeu', code: '+590', flag: '🇧🇱' },
  { name: 'São Cristóvão e Neves', code: '+1', flag: '🇰🇳' },
  { name: 'São Marinho', code: '+378', flag: '🇸🇲' },
  { name: 'São Martinho (França)', code: '+590', flag: '🇲🇫' },
  { name: 'São Martinho (Países Baixos)', code: '+1', flag: '🇸🇽' },
  { name: 'São Pedro e Miquelão', code: '+508', flag: '🇵🇲' },
  { name: 'São Tomé e Príncipe', code: '+239', flag: '🇸🇹' },
  { name: 'São Vicente e Granadinas', code: '+1', flag: '🇻🇨' },
  { name: 'Senegal', code: '+221', flag: '🇸🇳' },
  { name: 'Serra Leoa', code: '+232', flag: '🇸🇱' },
  { name: 'Sérvia', code: '+381', flag: '🇷🇸' },
  { name: 'Seicheles', code: '+248', flag: '🇸🇨' },
  { name: 'Singapura', code: '+65', flag: '🇸🇬' },
  { name: 'Síria', code: '+963', flag: '🇸🇾' },
  { name: 'Somália', code: '+252', flag: '🇸🇴' },
  { name: 'Sri Lanca', code: '+94', flag: '🇱🇰' },
  { name: 'Essuatíni', code: '+268', flag: '🇸🇿' },
  { name: 'Sudão', code: '+249', flag: '🇸🇩' },
  { name: 'Sudão do Sul', code: '+211', flag: '🇸🇸' },
  { name: 'Suécia', code: '+46', flag: '🇸🇪' },
  { name: 'Suíça', code: '+41', flag: '🇨🇭' },
  { name: 'Suriname', code: '+597', flag: '🇸🇷' },
  { name: 'Tailândia', code: '+66', flag: '🇹🇭' },
  { name: 'Taiwan', code: '+886', flag: '🇹🇼' },
  { name: 'Tajiquistão', code: '+992', flag: '🇹🇯' },
  { name: 'Tanzânia', code: '+255', flag: '🇹🇿' },
  { name: 'Território Britânico do Oceano Índico', code: '+246', flag: '🇮🇴' },
  { name: 'Timor-Leste', code: '+670', flag: '🇹🇱' },
  { name: 'Togo', code: '+228', flag: '🇹🇬' },
  { name: 'Tonga', code: '+676', flag: '🇹🇴' },
  { name: 'Trindade e Tobago', code: '+1', flag: '🇹🇹' },
  { name: 'Tunísia', code: '+216', flag: '🇹🇳' },
  { name: 'Turquemenistão', code: '+993', flag: '🇹🇲' },
  { name: 'Turquia', code: '+90', flag: '🇹🇷' },
  { name: 'Tuvalu', code: '+688', flag: '🇹🇻' },
  { name: 'Ucrânia', code: '+380', flag: '🇺🇦' },
  { name: 'Uganda', code: '+256', flag: '🇺🇬' },
  { name: 'Uruguai', code: '+598', flag: '🇺🇾' },
  { name: 'Usbequistão', code: '+998', flag: '🇺🇿' },
  { name: 'Vanuatu', code: '+678', flag: '🇻🇺' },
  { name: 'Vaticano', code: '+379', flag: '🇻🇦' },
  { name: 'Venezuela', code: '+58', flag: '🇻🇪' },
  { name: 'Vietname', code: '+84', flag: '🇻🇳' },
  { name: 'Wallis e Futuna', code: '+681', flag: '🇼🇫' },
  { name: 'Zâmbia', code: '+260', flag: '🇿🇲' },
  { name: 'Zimbabué', code: '+263', flag: '🇿🇼' }
];
