name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install Dependencies
        run: npm ci

      - name: Build Web App
        run: npm run build

      - name: Capacitor Sync
        run: npx cap sync android

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Cache Android Keystore (Fixed SHA-1)
        uses: actions/cache@v4
        with:
          path: ~/.android/debug.keystore
          key: android-debug-keystore-v1

      - name: Build APK
        working-directory: ./android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug

      - name: EXTRAINDO SHA-1 PARA O FIREBASE
        run: |
          echo "COPIE E COLE O SEGUINTE CÓDIGO NO SEU FIREBASE CONSOLE:"
          keytool -list -v -keystore ~/.android/debug.keystore -alias androiddebugkey -storepass android -keypass android | grep "SHA1:"

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: android/app/build/outputs/apk/debug/app-debug.apk
